export type ProjectWorkpackage = {
  id: string;
  title: string;
  aliases?: string[];
  keywords?: string[];
  contacts?: Array<{ name?: string; email?: string }>;
  status?: "active" | "paused" | "done" | "unknown";
};

export type Project = {
  id: string;
  title: string;
  mailbox_folder: string;
  reference_md?: string;
  aliases?: string[];
  keywords?: string[];
  domains?: string[];
  contacts?: Array<{ name?: string; email?: string }>;
  workpackages?: ProjectWorkpackage[];
  description?: string;
  typical_subject_patterns?: string[];
  routing_priority?: number;
  do_not_route_if?: string[];
  updated_at?: string;
  schema_version?: number;
};

export type Topic = {
  id: string;
  title: string;
  mailbox_folder: string;
  aliases?: string[];
  keywords?: string[];
  domains?: string[];
  contacts?: Array<{ name?: string; email?: string; role?: string }>;
  typical_subject_patterns?: string[];
  routing_priority?: number;
  do_not_route_if?: string[];
  updated_at?: string;
  schema_version?: number;
};

export type EnvConfig = {
  MAIL_PROCESSOR_DATA_DIR: string;
  MAIL_PROCESSOR_STATE_FILE: string;
  MAIL_PROCESSOR_MSGS_DIR: string;
  MAIL_PROCESSOR_SUGGESTIONS_FILE: string;
  MAIL_PROCESSOR_CAPABILITIES_DIR: string;
  MAIL_PROCESSOR_LOCK_FILE: string;
  MAIL_PROCESSOR_LOCK_TTL_SECONDS: number;
  PROJECTS_JSON_PATH: string;
  TOPICS_JSON_PATH: string;
  MAIL_ROUTING_ENABLED: boolean;
  LOG_LEVEL: string;
  HIMALAYA_COMMAND: string;
  MAIL_SOURCE_FOLDER: string;
  MAIL_FETCH_LIMIT: number;
  MAIL_SCAN_MODE: "auto" | "tail" | "backfill";
  MAIL_ENVELOPE_PAGE_SIZE: number;
  MAIL_SELECT_MAX_SCAN_PAGES: number;
  MAIL_CURSOR_FILE: string;
  MAIL_INTER_MESSAGE_DELAY_MS: number;
  MAIL_INTER_MESSAGE_JITTER_MS: number;
  MAIL_MESSAGE_READ_TIMEOUT_MS: number;
  MAIL_MESSAGE_READ_RETRIES: number;
  MAIL_MESSAGE_READ_RETRY_BACKOFF_MS: number;
  MAIL_ROUTE_ACTION: "auto" | "copy" | "move";
  MAIL_COPY_SEMANTICS: "normal" | "acts_like_move";
  MAIL_ROUTE_STRICT: boolean;
  MAIL_USE_UIDPLUS: boolean;
  PROJECT_MATCH_THRESHOLD: number;
  NEEDS_REPLY_THRESHOLD: number;
  NEEDS_REPLY_NEGATIVE_HINTS: string[];
  MAIL_DEBUG_RETENTION_DAYS: number | null;
  LLM_BASE_URL: string;
  LLM_API_KEY: string;
  LLM_MODEL: string;
  LLM_ENABLED: boolean;
  LLM_TIMEOUT_MS: number;
  LLM_PROMPT_PATH?: string;
  MAIL_SANITIZE_ENABLED: boolean;
  MAIL_SANITIZE_MODE: "off" | "balanced" | "strict";
  MAIL_STRIP_TRACKING_PARAMS: boolean;
  MAIL_NEWSLETTER_FOOTER_TRIM: boolean;
  MAIL_HTML_MAX_CURRENT: number;
  MAIL_HTML_MAX_QUOTED: number;
};
